ServerName localhost

<VirtualHost *:8000>
    ServerName localhost
    UseCanonicalName Off
    DocumentRoot /app/code/public

    ErrorLog "|/bin/cat"
    CustomLog "|/bin/cat" combined

    SetEnvIfNoCase X-Forwarded-Proto "https" HTTPS=on

   <Directory /app/code/public>
        Options +FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>
</VirtualHost>
